# Generated by Django 5.1.6 on 2025-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("imdb_id", models.CharField(max_length=100)),
                ("original_title", models.CharField(max_length=100)),
                ("genres", models.CharField(max_length=100)),
                ("poster_path", models.CharField(max_length=100)),
                ("keywords", models.CharField(max_length=100)),
            ],
        ),
    ]
