# Generated by Django 5.1.6 on 2025-02-25 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("genre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("revenue", models.IntegerField(default=0)),
                ("vote_average", models.FloatField(default=0.0)),
                ("imdb_id", models.CharField(default="", max_length=100)),
                ("original_title", models.CharField(max_length=100)),
                ("overview", models.TextField(default="")),
                ("popularity", models.FloatField(default=0.0)),
                ("genres", models.CharField(default="", max_length=100)),
                ("poster_path", models.CharField(default="", max_length=100)),
                ("keywords", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MoviePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        default="dislike",
                        max_length=10,
                    ),
                ),
                (
                    "movie_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_preference",
                        to="movies.movie",
                    ),
                ),
                (
                    "user_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenrePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_id", models.CharField(default="", max_length=100)),
                (
                    "preference_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        default="dislike",
                        max_length=10,
                    ),
                ),
                (
                    "user_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id_fk", "genre_id")},
            },
        ),
    ]
