# Generated by Django 5.1.6 on 2025-02-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='GenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.CharField(default='', max_length=100)),
                ('preference_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='dislike', max_length=10)),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoviePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='dislike', max_length=10)),
                ('movie_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_preference', to='movies.movie')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id_fk', 'movie_id_fk')},
            },
        ),
    ]
