# Generated by Django 5.1.6 on 2025-02-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="overview",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="movie",
            name="popularity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="movie",
            name="revenue",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_average",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="keywords",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(default="", max_length=100),
        ),
    ]
