# Generated by Django 5.1.6 on 2025-02-22 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_overview_movie_popularity_movie_revenue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
        migrations.CreateModel(
            name='GenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='dislike', max_length=10)),
                ('genre_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id_fk', 'genre_id_fk')},
            },
        ),
        migrations.CreateModel(
            name='MoviePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='dislike', max_length=10)),
                ('movie_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_preference', to='movies.movie')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id_fk', 'movie_id_fk')},
            },
        ),
    ]
