# Generated by Django 5.1.6 on 2025-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_movie_overview_movie_popularity_movie_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrepreference',
            name='genre_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
