# Generated by Django 5.1.6 on 2025-02-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_genrepreference_genre_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="moviepreference",
            unique_together=set(),
        ),
    ]
