# Generated by Django 5.1.6 on 2025-02-24 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_moviepreference_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="genrepreference",
            name="genre_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="genrepreference",
            unique_together={("user_id_fk", "genre_id")},
        ),
    ]
